### ISSUE TITLE
Repeated declaration of global variable in fn_log.sqf

### ISSUE THREAD

**Issue by tspindler-cms** [xetra11/ReconMod#2]
`reconModName = "[ReconMod]";` in fn_log.sqf overwrites the global variable recondModName with each call. It's probably better to declare the global variable once in fn_init.sqf and the make it a [publicVariable](https://community.bistudio.com/wiki/publicVariable).

Further the global variable name should be prefixed with your [OFPEC](https://community.bistudio.com/wiki/OFPEC_tags) tag.

**Comment by xetra11** [comment]
Thanks a heap for helping me out with good practises!
